Numpy and Pandas Practice problems

1. Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.

In [2]:
import numpy as np
arr = np.arange(1, 21)
print(arr)
arr = arr.reshape(4, 5)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2. Create an array of 10 zeros and replace the 5th element with 100.

In [4]:
import numpy as np

arr = np.zeros(10)
print(arr)
arr[4] = 100

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.   0.   0.   0. 100.   0.   0.   0.   0.   0.]


3. Create a NumPy array of even numbers between 2 and 40."

In [5]:
import numpy as np

even_numbers = np.arange(2, 41, 2)   # start=2, stop=41 (exclusive), step=2

print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


4. Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.

In [7]:
import numpy as np

arr = np.random.randint(1, 101, size=15)

minimum = np.min(arr)
maximum = np.max(arr)
mean = np.mean(arr)
std_dev = np.std(arr)


print("Array:", arr)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Array: [72 36 74 85  6 61 84 52 11 20  3 18 20 65 43]
Minimum: 3
Maximum: 85
Mean: 43.333333333333336
Standard Deviation: 28.118005303047767


5. Given two arrays of sales and costs, calculate profit and profit percentage arrays.

In [8]:
import numpy as np


sales = np.array([1000, 2500, 800, 3200, 1500, 900])
costs = np.array([ 700, 1800, 600, 2100, 1200, 950])
profit = sales - costs
profit_percentage = (profit / costs) * 100
profit_percentage = np.round(profit_percentage, 2)
print("Sales:            ", sales)
print("Costs:            ", costs)
print("Profit:           ", profit)
print("Profit %:         ", profit_percentage, "%")

Sales:             [1000 2500  800 3200 1500  900]
Costs:             [ 700 1800  600 2100 1200  950]
Profit:            [ 300  700  200 1100  300  -50]
Profit %:          [42.86 38.89 33.33 52.38 25.   -5.26] %


6. Create a 6×6 random matrix and compute row sums, column sums, and total sum.

In [9]:
import numpy as np


np.random.seed(42)

matrix = np.random.randint(1, 101, size=(6, 6))

print("6×6 Random Matrix:")
print(matrix)
print()

row_sums = matrix.sum(axis=1)

col_sums = matrix.sum(axis=0)


total_sum = matrix.sum()


print("Row sums:     ", row_sums)
print("Column sums:  ", col_sums)
print("Total sum:    ", total_sum)

6×6 Random Matrix:
[[ 52  93  15  72  61  21]
 [ 83  87  75  75  88 100]
 [ 24   3  22  53   2  88]
 [ 30  38   2  64  60  21]
 [ 33  76  58  22  89  49]
 [ 91  59  42  92  60  80]]

Row sums:      [314 508 192 215 327 424]
Column sums:   [313 356 214 378 360 359]
Total sum:     1980


7. Given stock prices, compute daily returns using vectorized NumPy operations.

In [10]:
import numpy as np

prices = np.array([100.0, 102.5, 101.0, 105.0, 107.5, 106.0, 110.0, 108.5, 112.0, 115.0])

daily_returns = prices[1:] / prices[:-1] - 1



print("Stock Prices:     ", prices)
print("Daily Returns:    ", np.round(daily_returns, 4))

Stock Prices:      [100.  102.5 101.  105.  107.5 106.  110.  108.5 112.  115. ]
Daily Returns:     [ 0.025  -0.0146  0.0396  0.0238 -0.014   0.0377 -0.0136  0.0323  0.0268]


8. Convert an array of annual interest rates into monthly rates using vectorization.

In [11]:
import numpy as np

annual_rates = np.array([0.03, 0.05, 0.06, 0.08, 0.12, 0.00])


monthly_rates = (1 + annual_rates) ** (1/12) - 1

monthly_rates_pct = np.round(monthly_rates * 100, 4)


print("Annual Rates (%):     ", annual_rates * 100)
print("Monthly Rates (%):    ", monthly_rates_pct)

Annual Rates (%):      [ 3.  5.  6.  8. 12.  0.]
Monthly Rates (%):     [0.2466 0.4074 0.4868 0.6434 0.9489 0.    ]


9. Normalize a given array of portfolio weights so that the sum becomes 1.

In [12]:
import numpy as np

raw_weights = np.array([30, 25, 20, 15, 10, 5])


normalized_weights = raw_weights / raw_weights.sum()


normalized_weights = np.round(normalized_weights, 4)

print("Raw weights:         ", raw_weights)
print("Sum of raw weights:  ", raw_weights.sum())
print("Normalized weights:  ", normalized_weights)
print("Sum after normalization:", normalized_weights.sum())

Raw weights:          [30 25 20 15 10  5]
Sum of raw weights:   105
Normalized weights:   [0.2857 0.2381 0.1905 0.1429 0.0952 0.0476]
Sum after normalization: 1.0000000000000002


10. Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]

a. Find:

i. mean

ii. max

iii. index of the max value

In [13]:
import pandas as pd


data = [1200, 1500, 1800, 2000, 2200]
sales = pd.Series(data)

print(sales)

# i. Mean
mean_value = sales.mean()

# ii. Maximum value
max_value = sales.max()

# iii. Index of the maximum value
max_index = sales.idxmax()

print("i.   Mean                 :", mean_value)
print("ii.  Maximum value        :", max_value)
print("iii. Index of max value   :", max_index)

0    1200
1    1500
2    1800
3    2000
4    2200
dtype: int64
i.   Mean                 : 1740.0
ii.  Maximum value        : 2200
iii. Index of max value   : 4


11. Create a DataFrame with Student Name + 3 subject marks:

Name | Math | Science | English

Then:

· Print only the Math column

· Print first 2 rows

· Print the shape

In [14]:
import pandas as pd

# Create the DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Math': [85, 92, 78, 96, 88],
    'Science': [90, 88, 95, 91, 87],
    'English': [82, 85, 89, 94, 90]
}

df = pd.DataFrame(data)

# Display the full DataFrame
print("Full DataFrame:")
print(df)
print()

# Tasks:
# 1. Print only the Math column
print("Math column only:")
print(df['Math'])
# Alternative: print(df.Math)

print("\nMath column (as DataFrame):")
print(df[['Math']])   # double brackets → keeps it as DataFrame

# 2. Print first 2 rows
print("\nFirst 2 rows:")
print(df.head(2))

# 3. Print the shape
print("\nShape of DataFrame:", df.shape)
print("→", df.shape[0], "rows and", df.shape[1], "columns")

Full DataFrame:
      Name  Math  Science  English
0    Alice    85       90       82
1      Bob    92       88       85
2  Charlie    78       95       89
3    Diana    96       91       94
4      Eve    88       87       90

Math column only:
0    85
1    92
2    78
3    96
4    88
Name: Math, dtype: int64

Math column (as DataFrame):
   Math
0    85
1    92
2    78
3    96
4    88

First 2 rows:
    Name  Math  Science  English
0  Alice    85       90       82
1    Bob    92       88       85

Shape of DataFrame: (5, 4)
→ 5 rows and 4 columns


12. Using this DataFrame:

df = pd.DataFrame({

"Account": [101,102,103,104],

"Balance": [5000, 15000, 7000, 12000]

})

Filter rows where:

· Balance > 8000

· Balance between 6000 and 13000

In [15]:
import pandas as pd

# Create the DataFrame
df = pd.DataFrame({
    "Account": [101, 102, 103, 104],
    "Balance": [5000, 15000, 7000, 12000]
})

print("Original DataFrame:")
print(df)
print()
high_balance = df[df['Balance'] > 8000]
print("Accounts with Balance > 8000:")
print(high_balance)
mid_balance = df[df['Balance'].between(6000, 13000)]
# or: df[(df['Balance'] >= 6000) & (df['Balance'] <= 13000)]

print("\nAccounts with Balance between 6000 and 13000:")
print(mid_balance)

Original DataFrame:
   Account  Balance
0      101     5000
1      102    15000
2      103     7000
3      104    12000

Accounts with Balance > 8000:
   Account  Balance
1      102    15000
3      104    12000

Accounts with Balance between 6000 and 13000:
   Account  Balance
2      103     7000
3      104    12000
